version: "3.0"
services:
    web:
       build: .
       image: onlinepublishing
       container_name: onlinepublishing
       ports:
       - "8002:8002"
       volumes:
       - .:/onlinepublishing
       command:
         - /bin/bash
         - -c
         - |
           python3 manage.py makemigrations
           python3 manage.py migrate
           python3 manage.py runserver 0.0.0.0:8002
