# Generated by Django 2.1.4 on 2019-02-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Envir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='操作类型')),
            ],
            options={
                'verbose_name_plural': '代码所在环境',
                'db_table': 'envir',
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('operator', models.IntegerField(verbose_name='操作人')),
                ('operate_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('detail', models.TextField(null=True, verbose_name='操作详情')),
            ],
            options={
                'verbose_name_plural': '操作日志',
                'db_table': 'log',
            },
        ),
        migrations.CreateModel(
            name='OperateType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='操作类型')),
            ],
            options={
                'verbose_name_plural': '操作类型',
                'db_table': 'operate_type',
            },
        ),
        migrations.CreateModel(
            name='Repository',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='代码仓库')),
                ('branch', models.CharField(default='develop', max_length=256, null=True, verbose_name='分支')),
                ('tag', models.CharField(max_length=256, null=True, verbose_name='分支tag')),
            ],
            options={
                'verbose_name_plural': '代码仓库',
                'db_table': 'repository',
            },
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256, verbose_name='更新包名称')),
                ('developer', models.CharField(max_length=256, null=True, verbose_name='开发员')),
                ('tester', models.CharField(max_length=256, null=True, verbose_name='测试员')),
                ('is_publish', models.SmallIntegerField(default='1', null=True, verbose_name='是否申请发版（1：申请发版，2：不用申请发版）')),
                ('notice_tester', models.TextField(null=True, verbose_name='测试须知')),
                ('notice_operator', models.TextField(null=True, verbose_name='运维须知')),
                ('system', models.CharField(max_length=64, null=True, verbose_name='所属项目')),
                ('sql', models.TextField(null=True, verbose_name='需要执行的sql')),
                ('creator', models.IntegerField(verbose_name='创建人')),
                ('createtime', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updatetime', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('envir', models.ForeignKey(on_delete=True, to='test_online_publishing.Envir', verbose_name='所在环境（1：开发环境；5：测试环境；15：预生产环境（dev）；15：生产环境）')),
                ('repository_id', models.ForeignKey(on_delete=True, to='test_online_publishing.Repository', verbose_name='代码仓库id，对应repository表')),
            ],
            options={
                'verbose_name_plural': '更新包列表',
                'db_table': 'task_list',
            },
        ),
        migrations.AddField(
            model_name='log',
            name='operate_type',
            field=models.ForeignKey(on_delete=True, to='test_online_publishing.OperateType', verbose_name='操作类型（1：开发提交任务；5：更新到测试环境；10：更新到预生产环境；15：更新到生产环境）'),
        ),
    ]
