# Generated by Django 2.1.4 on 2019-02-05 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_online_publishing', '0002_auto_20190205_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='operate_type',
            field=models.ForeignKey(db_constraint=False, on_delete=True, to='test_online_publishing.OperateType', verbose_name='操作类型（1：开发提交任务；5：更新到测试环境；10：更新到预生产环境；15：更新到生产环境）'),
        ),
        migrations.AlterField(
            model_name='log',
            name='operator',
            field=models.IntegerField(blank=True, null=True, verbose_name='操作人'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='envir',
            field=models.ForeignKey(db_constraint=False, on_delete=True, to='test_online_publishing.Envir', verbose_name='所在环境（1：开发环境；5：测试环境；15：预生产环境（dev）；15：生产环境）'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='repository_id',
            field=models.ForeignKey(db_constraint=False, on_delete=True, to='test_online_publishing.Repository', verbose_name='代码仓库id，对应repository表'),
        ),
    ]
