# Generated by Django 2.1.4 on 2019-02-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_online_publishing', '0003_auto_20190205_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='operator',
            field=models.IntegerField(verbose_name='操作人'),
        ),
    ]
