# Generated by Django 2.1.4 on 2019-02-08 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_online_publishing', '0004_auto_20190205_1736'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='envir',
        ),
        migrations.RemoveField(
            model_name='tasklist',
            name='repository_id',
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='is_publish',
            field=models.SmallIntegerField(default='1', null=True, verbose_name='是否申请发版（1：申请发版，0：不用申请发版）'),
        ),
    ]
