# Generated by Django 2.1.4 on 2019-02-09 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_online_publishing', '0005_auto_20190208_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklist',
            name='envir',
            field=models.ForeignKey(db_constraint=False, default=1, on_delete=True, to='test_online_publishing.Envir', verbose_name='所在环境（1：开发环境；5：测试环境；10：预生产环境（dev）；15：生产环境）'),
        ),
        migrations.AddField(
            model_name='tasklist',
            name='repository_id',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=True, to='test_online_publishing.Repository', verbose_name='代码仓库id，对应repository表'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='name',
            field=models.CharField(help_text='更新包名称', max_length=256, verbose_name='更新包名称'),
        ),
    ]
