# Generated by Django 2.1.4 on 2019-02-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_online_publishing', '0006_auto_20190209_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='repository_id',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='repository_id',
            field=models.ManyToManyField(db_constraint=False, default=None, to='test_online_publishing.Repository', verbose_name='代码仓库id，对应repository表'),
        ),
    ]
