# Generated by Django 2.1.4 on 2019-02-24 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_online_publishing', '0007_auto_20190224_1136'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='tasklist',
            table='task',
        ),
    ]
