# Generated by Django 2.0.8 on 2019-02-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_online_publishing', '0008_auto_20190224_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='repository_id',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='repositorys',
            field=models.ManyToManyField(db_constraint=False, default=None, to='test_online_publishing.Repository', verbose_name='代码仓库'),
        ),
    ]
