# Generated by Django 2.0.8 on 2019-02-25 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_online_publishing', '0009_auto_20190224_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='task_id',
            field=models.ForeignKey(db_constraint=False, default=None, on_delete=True, to='test_online_publishing.TaskList', verbose_name='任务id'),
        ),
        migrations.AlterField(
            model_name='log',
            name='operate_type',
            field=models.ForeignKey(db_constraint=False, on_delete=True, to='test_online_publishing.OperateType', verbose_name='操作类型（1：开发提交任务；5：更新到本地环境；10：更新到dev环境；15：更新到dev2环境）'),
        ),
    ]
