# Generated by Django 2.0.8 on 2019-02-25 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test_online_publishing', '0010_auto_20190225_0054'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='task_id',
            new_name='task',
        ),
    ]
